### ISSUE TITLE
Failure to install via pip - No module named 'connection'

### ISSUE THREAD

**Issue by ajmas** [crustymonkey/py-sonic#10]
I am attempting to install via pip (as provided by MacPorts python 2.7) on MacOSX 10.10.4 and I get the following failure:

    Collecting py-sonic
      Downloading py-sonic-0.3.4.tar.gz
        Complete output from command python setup.py egg_info:
        Traceback (most recent call last):
          File "<string>", line 20, in <module>
          File "/private/tmp/pip-build-l9dx8wop/py-sonic/setup.py", line 21, in <module>
            from libsonic import __version__ as version
          File "/private/tmp/pip-build-l9dx8wop/py-sonic/libsonic/__init__.py", line 30, in <module>
            from connection import *
        ImportError: No module named 'connection'

Any suggestions? I am new to using pip.

**Comment by crustymonkey** [comment]
This is odd.  I've not heard of anyone having this issue before.  I don't have a mac to test with, but I think I have an idea of what the problem is.  I should be able to tackle this during this week.  I'll update here when that happens.

In the meantime, would you be willing to download the source from here (github) and try installing "the old fashioned way" (below) to see if you get the same issue?

```bash
tar -xvzf py-sonic*
cd py-sonic*
python setup.py install
```

**Comment by ajmas** [comment]
The old fashioned way worked. 

André-John

**Comment by crustymonkey** [comment]
Good to know that the old fashioned way works, but I'll see if I can replicate the pip problem.  Like I said, I don't have a mac to test with, but I can at least try on linux in a virtualenv.

**Comment by ajmas** [comment]
I just tested this in a Ubuntu Server VM (running using VirtualBox) and specifying the following works:

     pip install cy-sonic 

Further investigation on the Mac side shows that while I was using Python 2.7, the version of Pip I was using what the one from Python 3.4. Changing the pip version being using to be the one from Python 2.7 resolved the issue.

For anyone else:

  sudo port select --set pip pip27

You can close this as 'user environment misconfiguration'.

**Comment by Phyks** [comment]
Reproducible here, working in a Py3 venv.

This definitely is a Py2 vs Py3 thing, and would be worse fixing I think.
