### ISSUE TITLE
 pip install crashes

### ISSUE THREAD

**Issue by unhammer** [crustymonkey/py-sonic#14]
See 
[pip.log.txt](https://github.com/crustymonkey/py-sonic/files/121646/pip.log.txt)
and
https://github.com/rattboi/mopidy-subsonic/issues/16#issuecomment-181363721

**Comment by crustymonkey** [comment]
This should now be fixed in 0.4.1.  I've changed the method in which the SSL discovery is done, and this should also be forward compatible.
