### ISSUE TITLE
res.info().getheader('Content-Type') gives error "'HTTPMessage' object has no attribute 'getheader'"

### ISSUE THREAD

**Issue by n1ck3** [crustymonkey/py-sonic#20]
The function on line `2689` in `connection.py`:

```
    def _doBinReq(self, req):
        res = self._opener.open(req)
        contType = res.info().getheader('Content-Type')
        if contType:
            if contType.startswith('text/html') or \
                    contType.startswith('application/json'):
                dres = json.loads(res.read())
                return dres['subsonic-response']
        return res
```

Throws the error:

`'HTTPMessage' object has no attribute 'getheader'`

---

Replacing `getheader()` with `get()` resolves the issue. I found this solution [here](https://github.com/wialon/python-wialon/issues/8) when researching the issue.

**Comment by crustymonkey** [comment]
Thanks for the bug report.  It looks like the fix is pretty simple.  I should have some time to get this taken care of this weekend.

**Comment by crustymonkey** [comment]
All right, looks like this was only affecting the python3 branch.  This has been fixed, so a git pull should clear this up for you.
