### ISSUE TITLE
req: merge in python3 support + new release

### ISSUE THREAD

**Issue by ejstacey** [crustymonkey/py-sonic#21]
Hi!

I see you have python3 working in a branch.  I use libsonic for a Subsonic skill with the Mycroft voice assistant system (https://mycroft.ai).  They recently switched to python3.  I am moving my module over to python3, but I have py-sonic as a dependency, and I can't 'pip install' the python3-compatible version.  This means the skill isn't able to be nicely distributed/used without the users doing some extra work to install the python3 branch of py-sonic.

Are you able to merge in the python3 support and release a new version to pip (PyPI?)?

Thanks!

**Comment by crustymonkey** [comment]
I'm actually planning on just cutting over to python 3 and moving forward by *only* support Py 3.  It's just a matter of getting that bit of work done.

**Comment by ejstacey** [comment]
Fair enough, thanks!

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by crustymonkey** [comment]
I forgot to update this way back when, but I did make py-sonic python3 only after version 0.6.2
