### ISSUE TITLE
Scrobble does not support 'time'

### ISSUE THREAD

**Issue by dathbe** [crustymonkey/py-sonic#31]
The scrobble function in libsonic does not seem to support specifying the play_date time.  Documentation here:
http://www.subsonic.org/pages/api.jsp#scrobble

**Comment by dathbe** [comment]
Update:  It does appear to be supported, but not documented (https://stuffivelearned.org/doku.php?id=programming:python:py-sonic#scrobble_self_sid_submission_true).  I'm able to now set a time, but it's not clear to me what the code is expecting for the ```listenTime``` variable.  Inputting an int in microseconds since 1970 gives me a date in 1764??  I wasn't around in 1764, so I can't vouch for anyone having listened to the song then.

**Comment by crustymonkey** [comment]
Yeah, this is something I do throughout the library, which is convert from the standard unix timestamp to the non-standard Java BS of milliseconds as an int.  I'd rather have people just use `time.time()` calcs in python and pass that value than adhere to java stupidity.

**Comment by dathbe** [comment]
The thought makes sense. A note about it in the docs would be useful.
