### ISSUE TITLE
Misleading parameter baseurl

### ISSUE THREAD

**Issue by c-yco** [crustymonkey/py-sonic#6]
Hi, 

when using baseurl with something like 'http://hostname/madsonic' and having port set as '8885'
the constructed url gets 'http://hostname/madsonic:8885/rest' which is wrong as the port has to come directly after the hostname. 

I think it would be better to add an parameter hostname so you can construct the url by HOSTNAME + PORT + BASEURL

I am not sure why it seems that I am the first one running into this, perhaps its also an missunderstanding on my side.

**Comment by crustymonkey** [comment]
Admittedly, the documentation is a little confusing, and I will fix it.  What you want to use is the "serverPath" argument for everything after the "baseUrl" and "port".  Essentially, you would have something like the following:

```python
libsonic.Connection(baseUrl='http://hostname', port=8885, serverPath='/madsonic/rest')
```

That said, a rename, or at least a documentation clarification, are probably in order.

**Comment by c-yco** [comment]
This is exactly what I have done, so perhaps rename the parameter and change documentation in the next version..

**Comment by crustymonkey** [comment]
Added more documentation in 0.3.3.  Closing
